<a href="https://colab.research.google.com/github/sulabola/Deep_Learning_with_PyTorch/blob/main/Create_a_Basic_Neural_Network_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here we create a basic neural network using Iris data set. More details of the data avaibale in following link.

Link: https://en.wikipedia.org/wiki/Iris_flower_data_set

In the dataset we have 4 inputs/features and one output (class)

In [1]:
import torch
import torch.nn as nn ### nn stands for neural network
import torch.nn.functional as F ### This allow us to move data forward in out function

In [4]:
### Creat a model class that inherits nn.Module

class Model(nn.Module):

  ### Input layer (4 features of the flowers) --> Hidden layer1 (with some number of neurons) --> ... --> Output (3 class of iris flowers)

  def __init__(self, in_features = 4, h1=8, h2=9, out_features=3):

    ### self is how Python instances hold state, and nn.Module cleverly hooks into it to automatically track layers, parameters, and buffers for you.

    ### Initiate our nn.Module
    super().__init__()
    ### Setup layers
    self.fc1 = nn.Linear(in_features, h1) ### First hidden layer. This layer is fully connected, and thus we use "nn.Linear". "fc" = Fully Connected.
    self.fc2 = nn.Linear(h1, h2)  ### Second hidden layer. We are going from h1 to h2.
    self.out = nn.Linear(h2, out_features)

  ### Now we need to create a function to move everything forward

  def forward(self, x): ### We create a variable x to tract everything

    x = F.relu(self.fc1(x)) ### We send the output through rectified linear unit (push into the first layer)
    x = F.relu(self.fc2(x)) ### (Push into the second layer)
    x = self.out(x)

    return x

In [5]:
### Now we have created the module. Before turn it on, we need a manual seed (becase nn includes randomization).

torch.manual_seed(41)

### Create an instance of the model

model = Model() ### We use "Model" because out Model calss is "Model"

Import Data

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
### Load Data using a URL

### We are downloading data from GitHub for repository for Iris --> Choose "raw" data

url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)
my_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
my_df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [19]:
my_df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [23]:
### Class column is now call "species" and currently we have text. We like to change it (string --> Intiger).

my_df['variety'] = my_df['species'].replace({'setosa': 0.0, 'versicolor': 1.0, 'virginica': 2.0})
my_df

/tmp/ipykernel_168/2078510128.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df['variety'] = my_df['species'].replace({'setosa': 0.0, 'versicolor': 1.0, 'virginica': 2.0});

     sepal_length  sepal_width  petal_length  petal_width    species  variety
0             5.1          3.5           1.4          0.2     setosa      0.0
1             4.9          3.0           1.4          0.2     setosa      0.0
2             4.7          3.2           1.3          0.2     setosa      0.0
3             4.6          3.1           1.5          0.2     setosa      0.0
4             5.0          3.6           1.4          0.2     setosa      0.0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica      2.0
146           6.3          2.5           5.0          1.9  virginica      2.0
147           6.5          3.0           5.2          2.0  virginica      2.0
148           6.2          3.4           5.4          2.3  virginica      2.0
149           5.9          3.0           5.1          1.8  virginica      2.0

[150 rows x 6 columns]

In [24]:
## Train and Test Split

### Features
X = my_df.drop(['species','variety'], axis=1)

### Output
y = my_df['variety']

In [25]:
X

### X is a dataframe. We want to convert to numpy arrays.

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [26]:
X = X.values
y = y.values

In [28]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [29]:
y[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
### In order to get train and test data, we need sklearn

from sklearn.model_selection import train_test_split

In [31]:
### Train and test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41) ### Leave 20% for testing