<a href="https://colab.research.google.com/github/sulabola/Deep_Learning_with_PyTorch/blob/main/Create_a_Basic_Neural_Network_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here we create a basic neural network using Iris data set. More details of the data avaibale in following link.

Link: https://en.wikipedia.org/wiki/Iris_flower_data_set

In the dataset we have 4 inputs/features and one output (class)

In [37]:
import torch
import torch.nn as nn ### nn stands for neural network
import torch.nn.functional as F ### This allow us to move data forward in out function

In [38]:
### Creat a model class that inherits nn.Module

class Model(nn.Module):

  ### Input layer (4 features of the flowers) --> Hidden layer1 (with some number of neurons) --> ... --> Output (3 class of iris flowers)

  def __init__(self, in_features = 4, h1=8, h2=9, out_features=3):

    ### self is how Python instances hold state, and nn.Module cleverly hooks into it to automatically track layers, parameters, and buffers for you.

    ### Initiate our nn.Module
    super().__init__()
    ### Setup layers
    self.fc1 = nn.Linear(in_features, h1) ### First hidden layer. This layer is fully connected, and thus we use "nn.Linear". "fc" = Fully Connected.
    self.fc2 = nn.Linear(h1, h2)  ### Second hidden layer. We are going from h1 to h2.
    self.out = nn.Linear(h2, out_features)

  ### Now we need to create a function to move everything forward

  def forward(self, x): ### We create a variable x to tract everything

    x = F.relu(self.fc1(x)) ### We send the output through rectified linear unit (push into the first layer)
    x = F.relu(self.fc2(x)) ### (Push into the second layer)
    x = self.out(x)

    return x

In [39]:
### Now we have created the module. Before turn it on, we need a manual seed (becase nn includes randomization).

torch.manual_seed(41)

### Create an instance of the model

model = Model() ### We use "Model" because out Model calss is "Model"

Import Data

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [41]:
### Load Data using a URL

### We are downloading data from GitHub for repository for Iris --> Choose "raw" data

url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)
my_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
my_df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [43]:
my_df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [44]:
### Class column is now call "species" and currently we have text. We like to change it (string --> Intiger).

my_df['variety'] = my_df['species'].replace({'setosa': 0.0, 'versicolor': 1.0, 'virginica': 2.0})
my_df

/tmp/ipykernel_168/3652329027.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df['variety'] = my_df['species'].replace({'setosa': 0.0, 'versicolor': 1.0, 'virginica': 2.0})

     sepal_length  sepal_width  petal_length  petal_width    species  variety
0             5.1          3.5           1.4          0.2     setosa      0.0
1             4.9          3.0           1.4          0.2     setosa      0.0
2             4.7          3.2           1.3          0.2     setosa      0.0
3             4.6          3.1           1.5          0.2     setosa      0.0
4             5.0          3.6           1.4          0.2     setosa      0.0
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica      2.0
146           6.3          2.5           5.0          1.9  virginica      2.0
147           6.5          3.0           5.2          2.0  virginica      2.0
148           6.2          3.4           5.4          2.3  virginica      2.0
149           5.9          3.0           5.1          1.8  virginica      2.0

[150 rows x 6 columns]

Prepare Data and Model

In [45]:
## Train and Test Split

### Features
X = my_df.drop(['species','variety'], axis=1)

### Output
y = my_df['variety']

In [46]:
X

### X is a dataframe. We want to convert to numpy arrays.

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [47]:
X = X.values
y = y.values

In [48]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [49]:
y[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
### In order to get train and test data, we need sklearn

from sklearn.model_selection import train_test_split

In [51]:
### Train and test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41) ### Leave 20% for testing

In [52]:
### Convert train and test features to tensors

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [53]:
### Convert train and test y labels to tensors (LongTensor = 64 bit)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [54]:
### Now we need to set a criterion to measure the error (how far the rediction away from true values)

criterion = nn.CrossEntropyLoss()

### Choose an Optimizer and learning rate

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

### The model parameters are weights in the layers

In [57]:
### If needed we can view the model paramters (with initial values):

list(model.parameters())

[Parameter containing:
 tensor([[-0.2636, -0.2734,  0.3005, -0.3308],
         [-0.2350,  0.2720, -0.3718,  0.2452],
         [ 0.3045,  0.1357,  0.0896,  0.1933],
         [ 0.3782,  0.0407, -0.3600,  0.4613],
         [ 0.3666, -0.0116, -0.2923, -0.1937],
         [-0.4415,  0.3314, -0.0434,  0.3445],
         [ 0.1883, -0.0992, -0.3197,  0.1740],
         [-0.3208, -0.1111,  0.2972, -0.2723]], requires_grad=True),
 Parameter containing:
 tensor([-0.0245, -0.0679,  0.0573,  0.4814,  0.2923, -0.1877,  0.4425, -0.1626],
        requires_grad=True),
 Parameter containing:
 tensor([[ 0.1456,  0.1463, -0.0107, -0.3290,  0.3324, -0.0817,  0.2408, -0.2121],
         [-0.0361,  0.3031, -0.3068,  0.0136, -0.0046, -0.3022, -0.0685, -0.3241],
         [ 0.0764,  0.0595,  0.2023,  0.0088, -0.1424, -0.1275, -0.1320,  0.2750],
         [ 0.1133, -0.3520,  0.0632, -0.0472,  0.2579, -0.1034,  0.3086,  0.1093],
         [-0.3185,  0.0744, -0.0807,  0.1770, -0.3035, -0.0259,  0.2337,  0.1253],
         [ 0.1664,  0.2993,  0.1444,  0.1149,  0.0729,  0.0233,  0.3077, -0.0815],
         [ 0.0465,  0.0049, -0.0977,  0.2585,  0.0198, -0.3007,  0.2398, -0.1170],
         [ 0.0346, -0.3206,  0.1403, -0.2425, -0.0401,  0.3035,  0.0846,  0.2948],
         [-0.1916, -0.3289, -0.2831, -0.1211, -0.1101, -0.0240,  0.2022,  0.3083]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.3468, -0.2051,  0.3039, -0.0589, -0.0997, -0.3476, -0.0578, -0.3142,
          0.2995], requires_grad=True),
 Parameter containing:
 tensor([[-0.1529, -0.1029,  0.0621,  0.1514,  0.2912, -0.0564, -0.2488,  0.2912,
          -0.0707],
         [ 0.1217, -0.2522, -0.2136, -0.0250, -0.1106,  0.0118,  0.1256,  0.0327,
          -0.1445],
         [-0.0078,  0.2576,  0.2920,  0.2779,  0.2205,  0.1830,  0.3304, -0.3098,
          -0.2921]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1991,  0.3204, -0.2358], requires_grad=True)]

Train Our Model

In [ ]:
### Before train the model, we need to know "epochs" (how many runs through all the train data)

epochs = 100

### As we go through the epochs, we need to tract losses to see whether the model is learning (erro is reducing).

losses = []

for i in range(epochs):

  ### For each epoch we need to fit the model and get a prediction
  y_pred = model.forward(X_train) ### We are passing training data

  ### Measure error/loss
  loss = criterion(y_pred,y_train)

  ### Keep track of losses
  losses.append(loss)

  ### In order to observe while training the model, we may print the result after every 10 epochs.
  if(i%%10) == 0:
    print(f'Epoch: {i} and Loss: {loss}')

  ### Do backpropagation
  ### Feed back the error through the network to fine tune the weights